### PR TITLE
support copying the scale

### PR DESCRIPTION
**Pull request by spencer516**

### CODE REVIEW

**Comment by taras** [comment]
What does this copy do?

**Comment by spencer516** [comment]
The `copy` creates a duplicate of the scale. Part of the reason you were seeing that weird behavior is because `d3-axis` [copies the scale](https://github.com/d3/d3-axis/blob/master/src/axis.js#L43) before using it — and, because the `guid-domain-scale` here didn't implement it's own copy, copy would return a standard d3 scale, not an instance of the `guid-domain-scale`.

**Comment by ghost** [comment]
@spencer516 thanks, we tried this, it fixes our problem!

**Comment by taras** [comment]
Can you please pull this in :)

**Comment by spencer516** [comment]
Yes!

**Pull request merged**
